export const APP_ROUTES = {
  home: "/",
  about: "/about",
  contact: "/contact",
  login: "/auth/login",
  signup: "/auth/signup",
  register: "/register",
  dashboard: "/dashboard",
  profile: "/profile",
  settings: "/settings",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  notFound: "/not-found",
  tos: "/terms-of-service",
  privacy: "/privacy-policy",
  serverError: "/server-error",
  unauthorized: "/unauthorized",
  forbidden: "/forbidden",
  emailVerification: "/email-verification",
  emailVerificationSuccess: "/email-verification-success",
  emailVerificationFailed: "/email-verification-failed",
};
