export const APP_ROUTES = {
  home: "/",
  auth: "/auth",
  about: "/about",
  contact: "/contact",
  login: "/auth/login",
  signup: "/auth/signup",
  register: "/register",
  bioData: "/bio-data",
  dashboard: "/dashboard",
  profile: "/model",
  jobs: "/jobs",
  job: "/job-details",
  jobApplication: "/job-application",
  settings: "/settings",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  notFound: "/not-found",
  tos: "/terms-of-service",
  privacy: "/privacy-policy",
  serverError: "/server-error",
  unauthorized: "/unauthorized",
  forbidden: "/forbidden",
  emailVerification: "/email-verification",
  emailVerificationSuccess: "/email-verification/success",
  emailVerificationFailed: "/email-verification/failed",
};
